#datasource
spring:
  datasource:
    url: jdbc:mysql:///store
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml #mapper
  type-aliases-package: com.yuge.campustrading.pojo
  configuration:
    map-underscore-to-camel-case: true

user-address-max-count: 20
